version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: krash-kourse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: krash_kourse_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d krash_kourse_dev"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local